Android.bp: Mark qti_kernel_headers as recovery_available
error: vendor/qcom/opensource/recovery-ext/oem-recovery/Android.bp:25:1:
dependency "qti_kernel_headers" of "librecovery_updater" missing variant:
  os:android,image:recovery,arch:arm64_armv8-2a,sdk

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>